---
- hosts: web
  become: true
  tasks:
    - name: Installer Git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Ajouter le dépôt NodeSource pour Node.js 18
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      args:
        executable: /bin/bash

    - name: Installer Node.js 18
      apt:
        name: nodejs
        state: present

    - name: Créer dossier .ssh si absent
      file:
        path: /home/amaur/.ssh
        state: directory
        mode: '0700'
        owner: amaur
        group: amaur

    - name: Ajouter GitHub au known_hosts
      ansible.builtin.known_hosts:
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
        path: /home/amaur/.ssh/known_hosts
        state: present
      become: false
      become_user: amaur

    - name: S’assurer que le dossier api appartient à amaur
      file:
        path: /home/amaur/api
        owner: amaur
        group: amaur
        recurse: yes

    - name: Autoriser le dossier API comme safe pour git
      command: git config --global --add safe.directory /home/amaur/api
      become_user: amaur

    - name: Cloner le dépôt de l’API
      git:
        repo: 'git@github.com:AmauryRDV/Project_CI-CD.git'
        dest: /home/amaur/api
        version: main
        force: yes
        accept_hostkey: yes
        key_file: /home/amaur/.ssh/id_ed25519
      become_user: amaur


    - name: Installer les dépendances Node.js
      npm:
        path: /home/amaur/api
      become_user: amaur

    - name: Installer PM2 globalement
      npm:
        name: pm2
        global: yes
      become_user: amaur

    - name: Démarrer l'API avec node (nohup)
      command: nohup node /home/amaur/api/api/index.js > /home/amaur/api/api.log 2>&1 &
      args:
        chdir: /home/amaur/api
      become_user: amaur
