name: Déploiement Release

on:
  push:
    tags:
      - 'release-*'

jobs:
  run-release-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Donner les droits d'exécution au script
        run: chmod +x release.sh

      - name: Exécuter le script de release
        run: ./release.sh
